# 公共配置文件
spring:
  application:
    name: dimpleCompanionChain
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-m1qca2zg.sql.tencentcdb.com:29852/dimple_companion_chain?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: csj406915.
  # session 失效时间
  session:
    timeout: 86400
  mvc:
    path match:
#            路径匹配策略，默认是 ANT_PATH_MATCHER,解决springboot 2.6.x 版本路径匹配问题
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  servlet:
#    这样的配置有助于将你的应用与其他可能也在同一服务器上运行的服务或应用隔离开来，或者用于版本控制（例如，/v1/api/users 和 /v2/api/users）。
    context-path: /api
# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


