spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: root
    password: 
  session:
      timeout: 86400
  redis:
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT}"
    database: 0
server:
  address: 0.0.0.0
