# 公共配置文件
spring:
  profiles:
    default: dev
  application:
    name: dimpleCompanionChain
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dimple_companion_chain?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  # session 失效时间
  session:
    timeout: 86400
    # 将session存储到redis中
    store-type: redis
  # redis 配置
  redis:
    host: localhost
    port: 6379
    database: 0
  mvc:
    path match:
      #   这里是Knife4j出现的版本不匹配，路径匹配策略，默认是 ANT_PATH_MATCHER,解决springboot 2.6.x 版本路径匹配问题
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  servlet:
    #    这样的配置有助于将你的应用与其他可能也在同一服务器上运行的服务或应用隔离开来，或者用于版本控制（例如，/v1/api/users 和 /v2/api/users）。
    context-path: /api
    session:
      cookie:
    #     种cookie
        domain: localhost
# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


