version: '3'
services:
  your-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data: